[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "1234567890"
database = "restfulDemo"


[log]
#DebugLevel: "debug",
#InfoLevel:  "info",
#WarnLevel:  "warning",
#ErrorLevel: "error",
#FatalLevel: "fatal",
#PanicLevel: "panic",
level = "debug"
dir = "logs"
format = "text"
to = "stdout"